// <auto-generated />
namespace TimesheetSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class timesheet_database_v5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(timesheet_database_v5));
        
        string IMigrationMetadata.Id
        {
            get { return "201502070008576_timesheet_database_v5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
